import type { Metadata } from "next";
import { Theme } from "@radix-ui/themes";

import '@radix-ui/themes/styles.css';



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body style={{
        margin: 0,
        padding: 0,
        height: '100vh',
        boxSizing: 'border-box'
      }}>
        <Theme appearance="dark">
          {children}
        </Theme>
      </body>
    </html>
  );
}
